interface ElectronEnv {
  SKIP_VIDEOS?: boolean;
  ENABLE_LOGGER?: boolean;
  INPUT_VIDEO_ROTATION?: number;
  INPUT_VIDEO_ZOOM_FACTOR?: number;
  BASE_ANIMATION_DURATION?: number;
  FACE_RECOGNITION_CHECK_INTERVAL?: number;
  FACE_RECOGNITION_LOGOUT_TIME_WINDOW?: number;
  FACE_RECOGNITION_MAX_FACE_ANGLE?: number;
  FACE_RECOGNITION_MAX_FACE_DISTANCE?: number;
}

const env = window.electronAPI.env as ElectronEnv;

export const SKIP_VIDEOS = env.SKIP_VIDEOS;

export const INPUT_VIDEO_ROTATION = env.INPUT_VIDEO_ROTATION;
export const INPUT_VIDEO_ZOOM_FACTOR = env.INPUT_VIDEO_ZOOM_FACTOR;

export const ENABLE_LOGGER = env.ENABLE_LOGGER;

export const BASE_ANIMATION_DURATION = env.BASE_ANIMATION_DURATION;

export const FACE_RECOGNITION_CHECK_INTERVAL = env.FACE_RECOGNITION_CHECK_INTERVAL;
export const FACE_RECOGNITION_LOGOUT_TIME_WINDOW = env.FACE_RECOGNITION_LOGOUT_TIME_WINDOW;
export const FACE_RECOGNITION_MAX_FACE_ANGLE = env.FACE_RECOGNITION_MAX_FACE_ANGLE;
export const FACE_RECOGNITION_MAX_FACE_DISTANCE = env.FACE_RECOGNITION_MAX_FACE_DISTANCE;
